- name: "Restart nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "restarted"
- name: "Reload nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "reloaded"
- name: "Enable nginx"
  ansible.builtin.service:
    name: "nginx"
    enabled: true
- name: "Start nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "started"