version: '3.8'

services:
  backend:
    build: ./TODO/todo_backend
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Todo
    depends_on:
      - mongo

  frontend:
    build: ./TODO/todo_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: