---
- name: "Installation de l'infrastructure MERN"
  hosts: all
  become: no

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Vérification de Docker"
      community.docker.docker_host_info:
        containers: yes
      register: docker_info

    - name: "Affichage des informations Docker"
      ansible.builtin.debug:
        var: docker_info

  roles:
    - { role: docker, tags: ['docker'] }
    - { role: mongodb, tags: ['db'] }
    - { role: nodejs, tags: ['app'] }
    - { role: nginx, tags: ['web'] }